name: Success.yaml
on: 
  push:
    branches: 
      - v[0-9].[0-9]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - name: Start
        uses: actions/checkout@v4
       
      - name: Check Commit Format
        run: |
          commit=$(git log -1 --pretty=%B)
          if [[ $commit == *"#NORUN"* ]]; then
          exit 1
          fi
      
      - name: Checkout 
        uses: actions/checkout@v3
        
      - name: Run Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-results.txt'
          severity: 'CRITICAL'
        
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERNAME }}
          password: ${{ secrets.DOCKERTOKEN }}
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ADLC3-CA:${{github.sha}}
#注意在本地做：context: .
#Digitally sign the image
        
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 1
        
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1
        with:
          cosign-release: v2.1.1
        
      - name: Sign image with a key
        run: 
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}"
        env:
          TAGS: v2.1.1:${{github.sha}}
          COSIGN_PRIVATE_KEY: ${{ secrets.MYPRIVATEKEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGNKEY }}
      
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env: 
          SLACK_CHANNEL: mytest
          SLACK_MESSAGE: | 
            Name: Xu Chi
            Matriculation: A0285934N
            *Email*:e1221746@u.nus.edu
            *Git*: https://github.com/Lafoi98/CICD-Workshop
            *Image*: URL
          SLACK_TITLE: ADLC3-CA
          SLACK_USERNAME: MyTest
          SLACK_WEBHOOK: ${{ secrets.KEWEBHOOKUPL }}
              